[project]
authors = ["Chris Fonnesbeck <fonnesbeck@gmail.com>"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "pymc-examples"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.13.9,<3.14"
pymc = ">=5.26.1,<6"
jupyter = ">=1.1.1,<2"
ipykernel = ">=7.1.0,<8"
ipywidgets = ">=8.1.8,<9"
numpy = ">=2.3.5,<3"
arviz = ">=0.22.0,<0.23"
numpyro = ">=0.19.0,<0.20"
seaborn = ">=0.13.2,<0.14"
matplotlib = ">=3.10.8,<4"
pandas = ">=2.3.3,<3"
polars = ">=1.35.2,<2"
esbonio = ">=1.0.0,<2"
watermark = ">=2.5.0,<3"
nutpie = ">=0.16.3,<0.17"
numba = ">=0.62.1,<0.63"
scikit-learn = ">=1.7.2,<2"
blackjax = ">=1.3,<2"
networkx = ">=3.6,<4"
bokeh = ">=3.8.1,<4"
plotly = ">=6.5.0,<7"

[pypi-dependencies]
pymc-extras = ">=0.5.0, <0.6"
kaleido = ">=1.2.0, <2"
