[workspace]
authors = ["Chris Fonnesbeck <fonnesbeck@gmail.com>"]
channels = ["conda-forge"]
name = "pymc-examples"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
pymc = ">=5.22.0,<6"
nutpie = ">=0.14.3,<0.15"
numpyro = ">=0.18.0,<0.19"
numba = ">=0.61.2,<0.62"
ipywidgets = ">=8.1.7,<9"
arviz = ">=0.21.0,<0.22"
matplotlib = ">=3.10.3,<4"
python = ">=3.12.10,<3.13"
ipykernel = ">=6.29.5,<7"
blackjax = ">=1.2.4,<2"
watermark = ">=2.5.0,<3"
polars = ">=1.30.0,<2"
pytorch = ">=2.9.1,<3"
openblas = ">=0.3.29,<0.4"
