name: pymc-test-py38
channels:
- conda-forge
- defaults
dependencies:
- pip
- pytest-cov>=2.5
- pytest>=3.0
- python=3.8
- dask
- xhistogram
- pip:
  - "git+https://github.com/pymc-devs/pymc.git@main"
